name: Murder
author: TheNewHEROBRINE, ElektroPrinz
version: 1.0.3
api: [3.0.0]
main: Murder\MurderMain
load: POSTWORLD

permissions:
 murder:
  children:
   murder.command:
    children:
     murder.command.join:
      default: true
     murder.command.quit:
      default: true
     murder.command.setarena:
      default: op
