name: Murder
author: TheNewHEROBRINE
version: 0.9
api: ["3.0.0-ALPHA11"]
main: TheNewHEROBRINE\Murder\MurderMain
load: POSTWORLD

permissions:
 murder:
  children:
   murder.command:
    children:
     murder.command.join:
      default: true
     murder.command.quit:
      default: true
     murder.command.setarena:
      default: op
